# Generated by Django 2.2.1 on 2019-06-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recognition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recognition_text', models.CharField(max_length=200)),
                ('recognition_date', models.DateTimeField(verbose_name='date published')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
