# Generated by Django 2.2.1 on 2019-06-25 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0002_auto_20190626_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognition',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
